#!/usr/bin/env python3
"""AutoPoC — Proof of Concept Test Script

Generated by the PoC Execute agent. Tests the deployed Juice MCP HTTP service
according to the PoC plan.
"""

import json
import os
import sys
import time
import urllib.request
import urllib.error

# Configuration
SERVICE_URL = os.environ.get("SERVICE_URL", sys.argv[1] if len(sys.argv) > 1 else "")
MAX_RETRIES = 5
RETRY_DELAY = 10  # seconds

results = []


def test_scenario(name, description, method, path, body=None, expected_status=200,
                  validate_fn=None, timeout=30):
    """Run a single test scenario."""
    url = f"{SERVICE_URL.rstrip('/')}{path}"
    start = time.time()

    for attempt in range(MAX_RETRIES):
        try:
            if body is not None:
                data = json.dumps(body).encode("utf-8")
                req = urllib.request.Request(url, data=data, method=method)
                req.add_header("Content-Type", "application/json")
            else:
                req = urllib.request.Request(url, method=method)

            with urllib.request.urlopen(req, timeout=timeout) as resp:
                status = resp.status
                response_body = resp.read().decode("utf-8")

                if status == expected_status:
                    # Parse response for validation
                    try:
                        response_data = json.loads(response_body)
                    except json.JSONDecodeError:
                        response_data = None

                    # Run custom validation if provided
                    if validate_fn:
                        validation_error = validate_fn(response_data, response_body)
                        if validation_error:
                            result = {
                                "scenario_name": name,
                                "status": "fail",
                                "output": response_body[:2000],
                                "error_message": validation_error,
                                "duration_seconds": round(time.time() - start, 2),
                            }
                            results.append(result)
                            return result

                    result = {
                        "scenario_name": name,
                        "status": "pass",
                        "output": response_body[:2000],
                        "error_message": None,
                        "duration_seconds": round(time.time() - start, 2),
                    }
                    results.append(result)
                    return result
                else:
                    if attempt < MAX_RETRIES - 1:
                        print(f"  [{name}] Attempt {attempt + 1}/{MAX_RETRIES}: got status {status}, expected {expected_status}. Retrying in {RETRY_DELAY}s...",
                              file=sys.stderr)
                        time.sleep(RETRY_DELAY)
                        continue
                    result = {
                        "scenario_name": name,
                        "status": "fail",
                        "output": response_body[:2000],
                        "error_message": f"Expected status {expected_status}, got {status}",
                        "duration_seconds": round(time.time() - start, 2),
                    }
                    results.append(result)
                    return result

        except urllib.error.HTTPError as e:
            response_body = ""
            try:
                response_body = e.read().decode("utf-8")
            except Exception:
                pass

            if attempt < MAX_RETRIES - 1:
                print(f"  [{name}] Attempt {attempt + 1}/{MAX_RETRIES} HTTP {e.code}: {response_body[:200]}. Retrying in {RETRY_DELAY}s...",
                      file=sys.stderr)
                time.sleep(RETRY_DELAY)
            else:
                result = {
                    "scenario_name": name,
                    "status": "fail",
                    "output": response_body[:2000],
                    "error_message": f"HTTP Error {e.code}: {response_body[:500]}",
                    "duration_seconds": round(time.time() - start, 2),
                }
                results.append(result)
                return result

        except urllib.error.URLError as e:
            if attempt < MAX_RETRIES - 1:
                print(f"  [{name}] Attempt {attempt + 1}/{MAX_RETRIES} failed: {e}. Retrying in {RETRY_DELAY}s...",
                      file=sys.stderr)
                time.sleep(RETRY_DELAY)
            else:
                result = {
                    "scenario_name": name,
                    "status": "error",
                    "output": "",
                    "error_message": f"Service unreachable after {MAX_RETRIES} attempts: {e}",
                    "duration_seconds": round(time.time() - start, 2),
                }
                results.append(result)
                return result

        except Exception as e:
            result = {
                "scenario_name": name,
                "status": "error",
                "output": "",
                "error_message": str(e),
                "duration_seconds": round(time.time() - start, 2),
            }
            results.append(result)
            return result


# ========== VALIDATION FUNCTIONS ==========

def validate_manifest(data, raw):
    """Validate manifest response has expected structure."""
    if data is None:
        return "Response is not valid JSON"
    if "schema_version" not in data:
        return "Missing 'schema_version' field in manifest"
    if "areas" not in data:
        return "Missing 'areas' field in manifest"
    if not isinstance(data["areas"], list):
        return "'areas' should be a list"

    # Check for expected default categories in areas
    area_categories = [a.get("category") for a in data["areas"]]
    for expected_cat in ["general", "design", "writing"]:
        if expected_cat not in area_categories:
            return f"Expected default category '{expected_cat}' not found in manifest areas. Got: {area_categories}"

    # Check each area has trigger_hints and scopes
    for area in data["areas"]:
        if "trigger_hints" not in area:
            return f"Area '{area.get('category')}' missing 'trigger_hints'"
        if "scopes" not in area:
            return f"Area '{area.get('category')}' missing 'scopes'"

    return None  # pass


def validate_categories(data, raw):
    """Validate categories list contains defaults."""
    if data is None:
        return "Response is not valid JSON"
    if not isinstance(data, list):
        return f"Expected JSON array, got {type(data).__name__}"

    category_names = [c.get("name") if isinstance(c, dict) else str(c) for c in data]
    for expected_cat in ["general", "design", "writing"]:
        if expected_cat not in category_names:
            return f"Expected default category '{expected_cat}' not found. Got: {category_names}"

    return None  # pass


def validate_register_category(data, raw):
    """Validate category registration response."""
    if data is None:
        return "Response is not valid JSON"
    # The response should confirm the category was created
    # It could be the category object itself or a confirmation
    raw_lower = raw.lower()
    if "security" not in raw_lower and "name" not in raw_lower:
        return f"Response does not confirm 'security' category registration: {raw[:500]}"
    return None  # pass


def validate_save_constraint(data, raw):
    """Validate constraint save response includes an id."""
    if data is None:
        return "Response is not valid JSON"
    if isinstance(data, dict):
        if "id" not in data:
            return f"Expected 'id' field in saved constraint response. Keys: {list(data.keys())}"
    return None  # pass


def validate_recall_constraints(data, raw):
    """Validate that constraints can be listed and the saved one is present."""
    if data is None:
        return "Response is not valid JSON"
    if not isinstance(data, list):
        return f"Expected JSON array, got {type(data).__name__}"

    # Look for our saved constraint about API keys
    found = False
    for item in data:
        if isinstance(item, dict):
            statement = item.get("statement", "").lower()
            if "api" in statement or "key" in statement or "plain text" in statement:
                found = True
                break

    if not found:
        return f"Previously saved constraint about API keys not found in list of {len(data)} constraints"

    return None  # pass


# ========== TEST SCENARIOS ==========

print("=" * 60, file=sys.stderr)
print("Juice PoC Test Suite", file=sys.stderr)
print(f"Service URL: {SERVICE_URL}", file=sys.stderr)
print("=" * 60, file=sys.stderr)

# Scenario 1: Health Check / Manifest
print("\n[1/5] Testing: Health Check / Manifest...", file=sys.stderr)
test_scenario(
    name="health-check",
    description="Verify the Juice HTTP server is running and responds to the manifest endpoint",
    method="GET",
    path="/api/manifest",
    expected_status=200,
    validate_fn=validate_manifest,
    timeout=30,
)

# Scenario 2: List Categories
print("[2/5] Testing: List Categories...", file=sys.stderr)
test_scenario(
    name="list-categories",
    description="Retrieve the default category registry",
    method="GET",
    path="/api/categories",
    expected_status=200,
    validate_fn=validate_categories,
    timeout=15,
)

# Scenario 3: Register Category
print("[3/5] Testing: Register Category...", file=sys.stderr)
test_scenario(
    name="register-category",
    description="Register a new custom category",
    method="POST",
    path="/api/categories",
    body={"name": "security", "trigger_hints": ["auth", "tokens", "secrets"]},
    expected_status=200,
    validate_fn=validate_register_category,
    timeout=15,
)

# Scenario 4: Save Constraint
# Note: The actual API endpoint is /api/juices (not /api/constraints)
print("[4/5] Testing: Save Constraint...", file=sys.stderr)
test_scenario(
    name="save-constraint",
    description="Save a negative constraint via the HTTP API",
    method="POST",
    path="/api/juices",
    body={
        "statement": "Avoid storing API keys in plain text configuration files",
        "scope": "global",
        "category": "general",
        "triggers": ["api-key", "secrets", "config"],
        "confidence": 0.9,
        "strength": 0.8,
    },
    expected_status=200,
    validate_fn=validate_save_constraint,
    timeout=15,
)

# Scenario 5: Recall Constraints
# Note: The actual API endpoint is GET /api/juices (list all, then verify our saved one is there)
# The Juice API doesn't have a /api/recall endpoint; recall is done through MCP tools.
# We'll use GET /api/juices to list active constraints and verify ours appears.
print("[5/5] Testing: Recall Constraints...", file=sys.stderr)
test_scenario(
    name="recall-constraints",
    description="Recall constraints by listing active constraints and verifying saved one is present",
    method="GET",
    path="/api/juices?status=active",
    expected_status=200,
    validate_fn=validate_recall_constraints,
    timeout=15,
)

# ========== END SCENARIOS ==========

# Print summary to stderr
print("\n" + "=" * 60, file=sys.stderr)
passed = sum(1 for r in results if r["status"] == "pass")
failed = sum(1 for r in results if r["status"] in ("fail", "error"))
print(f"Results: {passed} passed, {failed} failed, {len(results)} total", file=sys.stderr)
for r in results:
    icon = "✅" if r["status"] == "pass" else "❌"
    print(f"  {icon} {r['scenario_name']}: {r['status']}", file=sys.stderr)
    if r["error_message"]:
        print(f"     Error: {r['error_message']}", file=sys.stderr)
print("=" * 60, file=sys.stderr)

# Output results as JSON to stdout
print(json.dumps({"results": results}, indent=2))

# Exit with appropriate code
has_failures = any(r["status"] in ("fail", "error") for r in results)
sys.exit(1 if has_failures else 0)
