apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juice-data
  namespace: juice
  labels:
    app.kubernetes.io/name: juice
    app.kubernetes.io/managed-by: autopoc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
